services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smart_home_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smart_home_energy}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smart_home_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: smart_home_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smart_home_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  smart_home_network: